// Renders the AI-facing markdown component references (ai/components/*.md)
// from the two machine catalogs. The JSON stays the tool-facing source of
// truth; these pages are a deterministic, per-component projection small
// enough for an assistant to read one at a time. Nothing here may invent a
// fact: every line is either fixed template prose or a catalog/composition
// value.

import prettier from 'prettier';

export const COMPONENT_DOCS_DIR = 'ai/components';
export const COMPONENT_DOCS_INDEX = 'README.md';

const GENERATED_NOTE =
  '<!-- Generated by scripts/sync-component-docs.mjs from ai/component-catalog.json and ai/component-composition.json. Do not edit; run `npm run catalog:sync`. -->';

const SOURCE_LABEL = { kerf: 'Kerf UI', webawesome: 'Web Awesome' };
const KIND_LABEL = {
  component: 'component',
  composition: 'CSS composition',
  recipe: 'production recipe',
};

// Escapes the few characters in catalog prose that markdown would otherwise
// read as inline HTML or emphasis (`<button>`, `--kui-edge-inset-*`).
const text = (value) => String(value).replace(/([<*])/g, '\\$1');
const code = (value) => `\`${value}\``;
const bullets = (items) => items.map((item) => `- ${item}`).join('\n');

// GitHub-style heading slug, used to deep-link a module heading such as
// "## `@kerfjs/ui/toolbar`" → #kerfjsuitoolbar.
export const headingSlug = (heading) =>
  heading
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');

/** Module headings (`## \`specifier\``) present in a signatures markdown file. */
export const signatureModules = (markdown) =>
  new Set(
    [...markdown.matchAll(/^## `([^`]+)`\s*$/gm)].map((match) => match[1]),
  );

const bareId = (key) => key.slice(key.indexOf(':') + 1);

function linker(entries) {
  const byId = new Map(entries.map((entry) => [entry.id, entry]));
  return (id) => {
    const entry = byId.get(id);
    return entry ? `[${entry.name}](./${entry.id}.md)` : code(id);
  };
}

function cardinality({ min, max }) {
  if (max === 'unbounded') return min === 0 ? 'any number' : `at least ${min}`;
  if (min === max) return `exactly ${min}`;
  return `${min}–${max}`;
}

function modulesOf(entry) {
  const specifiers = [
    entry.delivery.browserImport,
    entry.delivery.moduleImport,
    ...(entry.wiring ?? []).map((item) => item.import),
  ].filter(Boolean);
  return [...new Set(specifiers)];
}

function selectionSection(entry, link) {
  const parts = ['## When to use', '', text(entry.purpose)];
  const useWhen = entry.useWhen.filter((item) => item !== entry.purpose);
  if (useWhen.length) parts.push('', bullets(useWhen.map(text)));
  if (entry.avoidWhen.length)
    parts.push('', '**Not when:**', '', bullets(entry.avoidWhen.map(text)));
  const alternatives = entry.alternatives ?? [];
  if (alternatives.length)
    parts.push(
      '',
      '**Alternatives:**',
      '',
      bullets(
        alternatives.map(
          (alt) =>
            `${link(alt.id)} (${alt.relationship})${alt.when ? ` — ${text(alt.when)}` : ''}`,
        ),
      ),
    );
  return parts.join('\n');
}

function importsSection(entry) {
  const { delivery } = entry;
  const lines = [];
  const exports = entry.publicExports ?? [];
  const jsImport = delivery.browserImport ?? delivery.moduleImport;
  if (jsImport) {
    lines.push(
      `JavaScript: ${code(jsImport)}${exports.length ? ` — exports ${exports.map(code).join(', ')}` : ''}.`,
    );
  }
  if (delivery.browserImport && delivery.manualCssImport)
    lines.push(
      `CSS: the browser build of ${code(delivery.browserImport)} pulls its CSS automatically; import ${code(delivery.manualCssImport)} manually only without the \`browser\` export condition.`,
    );
  else if (delivery.manualCssImport)
    lines.push(`CSS: import ${code(delivery.manualCssImport)} once.`);
  if (delivery.themeCssImport)
    lines.push(`Theme CSS: import ${code(delivery.themeCssImport)} once.`);
  if (delivery.registrationImport)
    lines.push(
      `Registration: import ${code(delivery.registrationImport)} once (a side effect).`,
    );
  if (entry.customElement)
    lines.push(`Custom element: ${code(`<${entry.customElement}>`)}.`);
  for (const item of entry.wiring ?? [])
    lines.push(
      `Wiring: ${code(item.export)} from ${code(item.import)}${item.required ? ' (required)' : ' (optional)'}.`,
    );
  if (!lines.length)
    lines.push('Nothing to import: this is a reference composition.');
  lines.push(`Declared side effects: ${delivery.sideEffects.join(', ')}.`);
  return ['## Imports', '', bullets(lines)].join('\n');
}

function propsSection(entry, modules) {
  const parts = ['## Props'];
  const linked = modulesOf(entry).filter((specifier) =>
    modules.api.has(specifier),
  );
  if (linked.length)
    parts.push(
      '',
      `Exact prop names and types: ${linked
        .map(
          (specifier) =>
            `[${code(specifier)}](../public-api-signatures-v1.md#${headingSlug(code(specifier))})`,
        )
        .join(
          ', ',
        )} in \`public-api-signatures-v1.md\`. Do not infer props from examples.`,
    );
  else if (entry.source === 'webawesome')
    parts.push(
      '',
      `Typed JSX attributes: [\`webawesome-jsx-signatures-v1.md\`](../webawesome-jsx-signatures-v1.md) (import \`@kerfjs/ui/webawesome\` for types only). Use the Web Awesome attribute API; do not reach into its shadow DOM.`,
    );
  else if (modulesOf(entry).length)
    parts.push(
      '',
      'Its signature is not in the bounded `public-api-signatures-v1.md` snapshot; read the emitted `.d.ts` for the module above.',
    );
  else parts.push('', 'No props: this entry has no JavaScript API.');
  if (entry.variants?.length)
    parts.push(
      '',
      '**Variants (configure, do not restyle):**',
      '',
      bullets(entry.variants.map(text)),
    );
  const cssProps = entry.cssValueProps ?? [];
  if (cssProps.length)
    parts.push(
      '',
      '**CSS-value props** (typed builders from `@kerfjs/ui/css-values`; raw CSS strings are rejected):',
      '',
      bullets(
        cssProps.map((prop) => {
          const details = [
            `${prop.grammar} grammar`,
            `raw values: ${prop.rawPolicy}`,
          ];
          if (prop.canonicalShorthands.length)
            details.push(
              `shorthands ${prop.canonicalShorthands.map(code).join(', ')}`,
            );
          if (prop.exceptionalShorthands.length)
            details.push(
              `exceptional (justify) ${prop.exceptionalShorthands.map(code).join(', ')}`,
            );
          if (prop.helpers.length)
            details.push(`helpers ${prop.helpers.map(code).join(', ')}`);
          const example = prop.examples[0]
            ? ` — e.g. ${code(prop.examples[0])}`
            : '';
          return `${code(prop.path)}: ${details.join('; ')}${example}`;
        }),
      ),
    );
  return parts.join('\n');
}

function compositionSection(entry, contract, link) {
  const lines = [];
  const { parents, children } = contract;
  if (parents.mode === 'root')
    lines.push(
      'Parents: used at the root of a screen or reference, not nested.',
    );
  else if (parents.mode === 'listed')
    lines.push(
      `Parents: only inside ${parents.entries.map((key) => link(bareId(key))).join(' or ')}.`,
    );
  else lines.push('Parents: any.');
  lines.push(`Contexts: ${contract.contexts.map(code).join(', ')}.`);
  if (children.mode === 'listed') {
    const required = children.requiredConcepts.length
      ? ` (required: ${children.requiredConcepts.map(link).join(', ')})`
      : '';
    lines.push(
      `Children: only ${children.concepts.map(link).join(', ')}${required}.`,
    );
  } else lines.push('Children: unrestricted.');
  if (entry.uses.length)
    lines.push(`Built from: ${entry.uses.map(link).join(', ')}.`);
  const parts = ['## Composition', '', bullets(lines)];
  if (contract.zones.length) {
    parts.push(
      '',
      'Zones (a zone is bound to JSX only through its listed prop; never assume the zone id is a prop):',
      '',
      bullets(
        contract.zones.map((zone) => {
          const prop = zone.jsx?.prop
            ? `JSX prop ${code(zone.jsx.prop)}`
            : 'no declared JSX prop';
          const exclusive = zone.exclusiveWith.length
            ? `; exclusive with ${zone.exclusiveWith.map(code).join(', ')}`
            : '';
          return `${code(zone.id)} — ${prop}; accepts ${zone.accepts.map(link).join(', ')}; ${cardinality(zone.cardinality)}${exclusive}.`;
        }),
      ),
    );
  }
  return parts.join('\n');
}

function stateSection(contract) {
  const parts = ['## State and wiring'];
  const owned = contract.state.filter((item) => item.owner === 'application');
  const other = contract.state.filter((item) => item.owner !== 'application');
  if (owned.length)
    parts.push(
      '',
      `**The app owns:** ${owned.map((item) => text(item.id)).join('; ')}.`,
    );
  if (other.length)
    parts.push(
      '',
      bullets(
        other.map(
          (item) =>
            `${text(item.id)} — ${item.owner}${item.required ? ' (required)' : ''}`,
        ),
      ),
    );
  const { wiring } = contract;
  if (wiring.helpers.length) {
    parts.push(
      '',
      `**Wiring:** ${wiring.helpers.map(code).join(', ')} ${wiring.required ? 'is required' : 'is optional'}.`,
    );
    if (wiring.obligations.length)
      parts.push('', bullets(wiring.obligations.map(text)));
  } else parts.push('', 'No wiring helper.');
  if (wiring.stateAttributes.length)
    parts.push(
      '',
      '**Wiring-owned state attributes** — never render, remove, or branch on these as app state:',
      '',
      bullets(
        wiring.stateAttributes.map(
          (attr) =>
            `${code(attr.name)} on ${code(attr.on)} (${code(attr.helper)}): ${text(attr.meaning)}`,
        ),
      ),
    );
  if (contract.responsive.behaviors.length)
    parts.push(
      '',
      `**Responsive (${contract.responsive.owner}-owned):**`,
      '',
      bullets(contract.responsive.behaviors.map((item) => text(item))),
    );
  return parts.join('\n');
}

function layoutSection(contract) {
  const { geometry, roles } = contract.layout;
  const parts = [
    '## Geometry',
    '',
    `Margin: ${geometry.margin} · border: ${geometry.border} · padding: ${geometry.padding} (layout role: ${roles.join(', ')}). \`self\` means the component already owns it — do not add wrapper padding, margin, or borders around it.`,
  ];
  if (geometry.notes?.length) parts.push('', bullets(geometry.notes.map(text)));
  return parts.join('\n');
}

function accessibilitySection(contract) {
  const obligations = contract.accessibility.obligations;
  return [
    '## Accessibility',
    '',
    obligations.length
      ? bullets(obligations.map(text))
      : 'No component-specific obligations beyond native semantics and a visible or accessible name for every control.',
  ].join('\n');
}

function stylingSection(entry, contract) {
  const { publicClasses, publicTokens } = contract.boundaries;
  const parts = [
    '## Styling boundary',
    '',
    'The component owns its own styles. Configure it through its props and variants; do not override its internals.',
  ];
  if (entry.source === 'webawesome')
    parts.push(
      '',
      'Theme it only through `@kerfjs/ui/webawesome.css` and cataloged tokens. Do not restyle its shadow DOM or uncataloged `::part()` targets (`KUI-L011`).',
    );
  if (publicClasses.length)
    parts.push(
      '',
      `Public class hooks (select for layout placement only, never to change the component's look): ${publicClasses.map(code).join(', ')}.`,
    );
  if (publicTokens.length)
    parts.push(
      '',
      `Public tokens it reads: ${publicTokens.map(code).join(', ')}. Set a token only where its public contract allows; prefer a prop.`,
    );
  if (entry.source === 'kerf')
    parts.push(
      '',
      'Everything else is internal: `kerf-ui-analyze` reports private or unknown `.kui-*` selectors (`KUI-L001`, `KUI-L010`), unknown or private tokens (`KUI-L002`, `KUI-L012`), and any application rule that restyles the component, forced dimensions included (`KUI-L019`).',
    );
  return parts.join('\n');
}

function diagnosticsSection(contract) {
  if (!contract.diagnostics.length) return null;
  return [
    '## Diagnostics',
    '',
    bullets(
      contract.diagnostics.map(
        (item) =>
          `${code(item.id)} (${item.severity}) when ${text(item.when)}: ${text(item.message)}`,
      ),
    ),
  ].join('\n');
}

function relatedSection(entry, link) {
  const related = [
    ...new Set([
      ...entry.uses,
      ...(entry.alternatives ?? []).map((alt) => alt.id),
    ]),
  ];
  const lines = [];
  if (related.length)
    lines.push(`Components: ${related.map(link).join(', ')}.`);
  const docs = [...new Set([entry.links.documentation, entry.links.recipe])];
  lines.push(
    `Docs: ${docs.map((path) => `[${code(path)}](../../${path})`).join(', ')}.`,
  );
  lines.push(`UX catalog route: ${code(entry.links.catalogRoute)}.`);
  return ['## Related', '', bullets(lines)].join('\n');
}

function renderPage(entry, contract, link, modules) {
  const tags = [
    SOURCE_LABEL[entry.source] ?? entry.source,
    KIND_LABEL[entry.kind] ?? entry.kind,
    entry.category,
    ...(entry.recommendation
      ? [`recommendation: ${entry.recommendation}`]
      : []),
  ];
  return [
    `# ${entry.name}`,
    GENERATED_NOTE,
    `${code(contract.key)} · ${tags.join(' · ')}`,
    ...(entry.description && entry.description !== entry.purpose
      ? [text(entry.description)]
      : []),
    selectionSection(entry, link),
    importsSection(entry),
    propsSection(entry, modules),
    compositionSection(entry, contract, link),
    stateSection(contract),
    layoutSection(contract),
    accessibilitySection(contract),
    stylingSection(entry, contract),
    diagnosticsSection(contract),
    relatedSection(entry, link),
  ]
    .filter(Boolean)
    .join('\n\n');
}

function renderIndex(entries) {
  const groups = new Map();
  for (const entry of entries) {
    const group = `${SOURCE_LABEL[entry.source] ?? entry.source} — ${entry.category}`;
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(entry);
  }
  const sections = [...groups].map(([group, members]) =>
    [
      `## ${group}`,
      '',
      bullets(
        members.map((entry) => {
          const note =
            entry.recommendation && entry.recommendation !== 'supported'
              ? ` (${entry.recommendation})`
              : '';
          return `[${entry.name}](./${entry.id}.md)${note} — ${text(entry.purpose)}`;
        }),
      ),
    ].join('\n'),
  );
  return [
    '# @kerfjs/ui component reference',
    GENERATED_NOTE,
    'One short page per catalog entry. Pick a component by the interface need from the one-line purposes below, then open only the pages you use. Each page lists when to use and avoid it, imports and CSS/registration side effects, where its exact props live, legal parents, zones with their JSX props and child counts, which state the app owns and which a wiring helper owns, geometry ownership, accessibility obligations, the styling boundary (configure through props; never override internals), and its `KUI-C` diagnostics.',
    'Exact prop and callback types live in [`public-api-signatures-v1.md`](../public-api-signatures-v1.md) (Web Awesome JSX in [`webawesome-jsx-signatures-v1.md`](../webawesome-jsx-signatures-v1.md)). Tools and linters read the canonical machine sources instead: [`component-catalog.json`](../component-catalog.json) (selection and delivery) and [`component-composition.json`](../component-composition.json) (composition), joined by `package:id`. Prefer a Kerf UI component over a Web Awesome element whenever both fit.',
    ...sections,
  ].join('\n\n');
}

/**
 * Renders every page. Returns a sorted Map of file name (relative to
 * ai/components/) → prettier-formatted markdown.
 */
export async function renderComponentDocs({
  catalog,
  composition,
  publicApiSignatures,
}) {
  const contracts = new Map(
    composition.entries.map((entry) => [entry.id, entry]),
  );
  const link = linker(catalog.entries);
  const modules = { api: signatureModules(publicApiSignatures) };
  const pages = new Map();
  pages.set(COMPONENT_DOCS_INDEX, renderIndex(catalog.entries));
  for (const entry of catalog.entries) {
    const contract = contracts.get(entry.id);
    if (!contract)
      throw new Error(
        `${entry.id} has no composition entry; run npm run composition:sync first.`,
      );
    pages.set(`${entry.id}.md`, renderPage(entry, contract, link, modules));
  }
  const formatted = new Map();
  for (const name of [...pages.keys()].sort()) {
    formatted.set(
      name,
      await prettier.format(`${pages.get(name)}\n`, {
        parser: 'markdown',
        singleQuote: true,
      }),
    );
  }
  return formatted;
}

/**
 * Compares rendered pages to the files on disk. `current` maps file name →
 * content for every *.md file present in the directory.
 */
export function diffComponentDocs(expected, current) {
  const problems = [];
  for (const [name, content] of expected) {
    if (!current.has(name)) problems.push(`missing ${name}`);
    else if (current.get(name) !== content) problems.push(`stale ${name}`);
  }
  for (const name of current.keys())
    if (!expected.has(name)) problems.push(`orphaned ${name}`);
  return problems.sort();
}
