// Generated by scripts/sync-component-catalog.mjs from ai/component-catalog.json. Do not edit.
export const generatedKerfCatalog = [
  {
    "id": "lucide-icon",
    "name": "LucideIcon",
    "category": "Foundation",
    "kind": "component",
    "source": "kerf",
    "description": "Decorative and meaningfully labeled Lucide-compatible icons.",
    "uses": [],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/lucide-icon.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "disclosure-arrow",
    "name": "DisclosureArrow",
    "category": "Foundation",
    "kind": "component",
    "source": "kerf",
    "description": "Indicate whether a disclosure control is open with an overridable 18px root-scaled visual and one shared rotation behavior.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/disclosure-arrow.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "webawesome-theme",
    "name": "Web Awesome theme",
    "category": "Foundation",
    "kind": "composition",
    "source": "kerf",
    "description": "Kerf palettes, typography, geometry, and focus styling across free Web Awesome component families.",
    "uses": [
      "wa-button",
      "wa-button-group",
      "wa-copy-button",
      "wa-dropdown",
      "wa-dropdown-item",
      "wa-checkbox",
      "wa-checkbox-group",
      "wa-color-picker",
      "wa-input",
      "wa-known-date",
      "wa-number-input",
      "wa-option",
      "wa-otp-input",
      "wa-radio",
      "wa-radio-group",
      "wa-rating",
      "wa-select",
      "wa-slider",
      "wa-switch",
      "wa-textarea",
      "wa-time-input",
      "wa-accordion",
      "wa-accordion-item",
      "wa-card",
      "wa-details",
      "wa-dialog",
      "wa-divider",
      "wa-drawer",
      "wa-page",
      "wa-scroller",
      "wa-split-panel",
      "wa-breadcrumb",
      "wa-breadcrumb-item",
      "wa-pagination",
      "wa-tab",
      "wa-tab-group",
      "wa-tab-panel",
      "wa-tree",
      "wa-tree-item",
      "wa-badge",
      "wa-callout",
      "wa-progress-bar",
      "wa-progress-ring",
      "wa-skeleton",
      "wa-spinner",
      "wa-tag",
      "wa-toast",
      "wa-toast-item",
      "wa-tooltip",
      "wa-animated-image",
      "wa-avatar",
      "wa-carousel",
      "wa-carousel-item",
      "wa-comparison",
      "wa-icon",
      "wa-markdown",
      "wa-qr-code",
      "wa-zoomable-frame",
      "wa-animation",
      "wa-format-bytes",
      "wa-format-date",
      "wa-format-number",
      "wa-include",
      "wa-intersection-observer",
      "wa-mutation-observer",
      "wa-popover",
      "wa-popup",
      "wa-random-content",
      "wa-relative-time",
      "wa-resize-observer"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "layout",
    "name": "Application layout",
    "category": "Foundation",
    "kind": "composition",
    "source": "kerf",
    "description": "Provide one reusable pane, toolbar, content stack, and content-item geometry across sidebars, main areas, and dialogs.",
    "uses": [],
    "demoSource": "ui/ux-demo/main.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "toolbar",
    "name": "Toolbar",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Leading, centered, and trailing toolbar composition.",
    "uses": [
      "toolbar-text",
      "toolbar-control-group"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/toolbar.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "toolbar-control-group",
    "name": "ToolbarControlGroup",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Contained, borderless, pressed, and single-control toolbar groups.",
    "uses": [
      "lucide-icon",
      "segmented-control"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/toolbar-control-group.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "toolbar-text",
    "name": "ToolbarText",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Large, default, and compact toolbar identity text.",
    "uses": [],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/toolbar-text.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "headers",
    "name": "Header composition",
    "category": "Structure",
    "kind": "composition",
    "source": "kerf",
    "description": "Page, dialog, and definition-list hierarchy.",
    "uses": [
      "page-header",
      "dialog-header",
      "value-table"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "page-header",
    "name": "PageHeader",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Page identity with an optional trailing action.",
    "uses": [],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/page-header.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "dialog-header",
    "name": "DialogHeader",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Dialog title, summary, icon, and action hierarchy.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/dialog-header.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "value-table",
    "name": "ValueTable",
    "category": "Structure",
    "kind": "component",
    "source": "kerf",
    "description": "Key/value rows with optional icons and aligned separators.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/value-table.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "menu",
    "name": "Menu composition",
    "category": "Navigation",
    "kind": "composition",
    "source": "kerf",
    "description": "Compose navigation with the same pane, content stack, item, and toolbar geometry used throughout the application.",
    "uses": [
      "menu-header",
      "menu-action-row",
      "menu-item"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "menu-header",
    "name": "MenuHeader",
    "category": "Navigation",
    "kind": "component",
    "source": "kerf",
    "description": "Split dormant title and badge content from an optional 44px action, or render the title cluster as a disclosure button.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/menu-header.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "menu-action-row",
    "name": "MenuActionRow",
    "category": "Navigation",
    "kind": "component",
    "source": "kerf",
    "description": "Keep a selectable primary row action and an independently named trailing action as sibling native controls inside one noninteractive visual row.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/menu-action-row.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "menu-item",
    "name": "MenuItem",
    "category": "Navigation",
    "kind": "component",
    "source": "kerf",
    "description": "Selectable, disabled, trailing, and multiline navigation rows.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/menu-item.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "tabs",
    "name": "AppTab",
    "category": "Navigation",
    "kind": "component",
    "source": "kerf",
    "description": "Roving-tabindex-ready tabs with protected application metadata and customizable close affordances.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/app-tab.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "tab-bar",
    "name": "TabBar",
    "category": "Navigation",
    "kind": "component",
    "source": "kerf",
    "description": "Controlled, reorderable tab strips with horizontal overflow.",
    "uses": [
      "tabs",
      "toolbar-control-group"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/tab-bar.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "segmented-control",
    "name": "SegmentedControl",
    "category": "Controls",
    "kind": "component",
    "source": "kerf",
    "description": "Controlled exclusive choices in toolbar, rounded-rectangle, and pill presentations.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/segmented-control.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "token-search-field",
    "name": "TokenSearchField",
    "category": "Controls",
    "kind": "component",
    "source": "kerf",
    "description": "Token-controlled, optionally collapsible search editor with ordered, editable, removable filter chips.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/token-search-field.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "resize",
    "name": "ResizableRegion",
    "category": "Controls",
    "kind": "component",
    "source": "kerf",
    "description": "Pointer and keyboard-operable split region with a customizable handle icon.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/resizable-region.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "select",
    "name": "Select",
    "category": "Controls",
    "kind": "component",
    "source": "kerf",
    "description": "Controlled Web Awesome select with grouped choices and rerender-stable icon slots.",
    "uses": [
      "lucide-icon",
      "wa-select",
      "wa-option"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/select.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "feedback",
    "name": "Feedback composition",
    "category": "Feedback",
    "kind": "composition",
    "source": "kerf",
    "description": "Banners, empty states, and labeled progress.",
    "uses": [
      "state-banner",
      "empty-state",
      "loading-spinner"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "state-banner",
    "name": "StateBanner",
    "category": "Feedback",
    "kind": "component",
    "source": "kerf",
    "description": "Polite status and assertive alert feedback with semantic tones.",
    "uses": [
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/state-banner.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "empty-state",
    "name": "EmptyState",
    "category": "Feedback",
    "kind": "component",
    "source": "kerf",
    "description": "Actionable empty and busy content states.",
    "uses": [
      "lucide-icon",
      "loading-spinner"
    ],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/empty-state.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "loading-spinner",
    "name": "LoadingSpinner",
    "category": "Feedback",
    "kind": "component",
    "source": "kerf",
    "description": "Meaningfully labeled or decorative progress.",
    "uses": [],
    "demoSource": "ui/ux-demo/main.tsx",
    "componentSource": "ui/src/loading-spinner.tsx",
    "documentation": "ui/docs/component-selection.md"
  },
  {
    "id": "recipe-app-shell",
    "name": "Desktop application shell",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Toolbar, navigation, content, and inspector shell with controlled resizing and explicit pane scroll owners.",
    "uses": [
      "toolbar",
      "toolbar-text",
      "toolbar-control-group",
      "menu-header",
      "menu-item",
      "page-header",
      "resize",
      "value-table",
      "layout"
    ],
    "demoSource": "ui/ux-demo/recipes/app-shell.tsx",
    "documentation": "ui/docs/recipes.md#desktop-application-shell"
  },
  {
    "id": "recipe-navigation-sidebar",
    "name": "Navigation sidebar",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Navigation sections with icon and iconless rows, a content-item surface, disclosure, and pane footer actions.",
    "uses": [
      "menu-header",
      "menu-item",
      "toolbar",
      "toolbar-control-group"
    ],
    "demoSource": "ui/ux-demo/recipes/navigation-sidebar.tsx",
    "documentation": "ui/docs/recipes.md#navigation-sidebar"
  },
  {
    "id": "recipe-workspace-header",
    "name": "Workspace header",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Page identity with primary, secondary, and overflow actions that relocate at narrow widths.",
    "uses": [
      "page-header",
      "state-banner",
      "layout"
    ],
    "demoSource": "ui/ux-demo/recipes/workspace-header.tsx",
    "documentation": "ui/docs/recipes.md#workspace-header"
  },
  {
    "id": "recipe-master-detail-dialog",
    "name": "Master-detail dialog",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Production modal containing a DialogHeader, navigable record master list, and ValueTable detail.",
    "uses": [
      "dialog-header",
      "menu-header",
      "menu-item",
      "value-table",
      "wa-dialog",
      "wa-button"
    ],
    "demoSource": "ui/ux-demo/recipes/master-detail-dialog.tsx",
    "documentation": "ui/docs/recipes.md#master-detail-dialog"
  },
  {
    "id": "recipe-composer-form",
    "name": "Composer form",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Label, help, validation, status, and action rhythm for a realistic publishing form.",
    "uses": [
      "select",
      "state-banner",
      "wa-input",
      "wa-textarea",
      "wa-button",
      "layout"
    ],
    "demoSource": "ui/ux-demo/recipes/composer-form.tsx",
    "documentation": "ui/docs/recipes.md#composer-form"
  },
  {
    "id": "recipe-list-workspace-states",
    "name": "List workspace states",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "Deterministic loading, empty, populated, stale refresh, and error states around one stable list workspace.",
    "uses": [
      "page-header",
      "state-banner",
      "empty-state",
      "loading-spinner",
      "layout"
    ],
    "demoSource": "ui/ux-demo/recipes/list-workspace-states.tsx",
    "documentation": "ui/docs/recipes.md#list-workspace-states"
  },
  {
    "id": "recipe-compact-toolbar",
    "name": "Compact toolbar choices and actions",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "A compact toolbar that distinguishes grouped commands, a visible exclusive choice, a longer Select, and one ordinary action.",
    "uses": [
      "toolbar",
      "toolbar-text",
      "toolbar-control-group",
      "segmented-control",
      "select",
      "lucide-icon"
    ],
    "demoSource": "ui/ux-demo/recipes/compact-toolbar.tsx",
    "documentation": "ui/docs/recipes.md#compact-toolbar-choices-and-actions"
  },
  {
    "id": "recipe-command-palette",
    "name": "Command palette",
    "category": "Recipes",
    "kind": "recipe",
    "source": "kerf",
    "description": "A copyable modal command search with grouped results, keyboard selection, empty state, and focus restoration.",
    "uses": [
      "dialog-header",
      "wa-dialog",
      "layout"
    ],
    "demoSource": "ui/ux-demo/recipes/command-palette.tsx",
    "documentation": "ui/docs/recipes.md#command-palette"
  }
] as const;

export const generatedWebAwesomeCatalog = [
  {
    "id": "wa-button",
    "name": "Button",
    "category": "Actions",
    "kind": "component",
    "source": "webawesome",
    "description": "Action control with semantic variants, appearances, loading, and icon support.",
    "uses": [
      "wa-icon",
      "wa-spinner"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-button-group",
    "name": "Button Group",
    "category": "Actions",
    "kind": "component",
    "source": "webawesome",
    "description": "Exceptional grouped actions; prefer Kerf SegmentedControl for exclusive choices.",
    "uses": [
      "wa-button"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-copy-button",
    "name": "Copy Button",
    "category": "Actions",
    "kind": "component",
    "source": "webawesome",
    "description": "Copies a supplied value and announces success or failure.",
    "uses": [
      "wa-icon",
      "wa-tooltip"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-dropdown",
    "name": "Dropdown",
    "category": "Actions",
    "kind": "component",
    "source": "webawesome",
    "description": "Action-menu primitive; prefer Kerf Select when choosing a value.",
    "uses": [
      "wa-dropdown-item",
      "wa-popup"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-dropdown-item",
    "name": "Dropdown Item",
    "category": "Actions",
    "kind": "component",
    "source": "webawesome",
    "description": "Action-menu row; prefer Kerf Select options for value selection.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-checkbox",
    "name": "Checkbox",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Binary form control with checked, indeterminate, and disabled states.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-checkbox-group",
    "name": "Checkbox Group",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Labels and validates a related set of checkboxes.",
    "uses": [
      "wa-checkbox"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-color-picker",
    "name": "Color Picker",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Color input with swatches, formats, opacity, and eyedropper support.",
    "uses": [
      "wa-button",
      "wa-button-group",
      "wa-input",
      "wa-popup"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-input",
    "name": "Input",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Text input with labels, hints, clear controls, and semantic appearances.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-known-date",
    "name": "Known Date",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental segmented field for partially or fully known dates.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-number-input",
    "name": "Number Input",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Numeric input with keyboard and stepper controls.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-option",
    "name": "Option",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Underlying ecosystem option; prefer choices passed to Kerf Select.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-otp-input",
    "name": "OTP Input",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental segmented one-time-password input.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-radio",
    "name": "Radio",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Single-choice control used inside a radio group.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-radio-group",
    "name": "Radio Group",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Labels and manages a mutually exclusive set of radios.",
    "uses": [
      "wa-radio"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-rating",
    "name": "Rating",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Interactive rating control with accessible labeling.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-select",
    "name": "Select",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Underlying ecosystem field; prefer Kerf Select for app UI.",
    "uses": [
      "wa-icon",
      "wa-popup",
      "wa-tag",
      "wa-option"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-slider",
    "name": "Slider",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Range input with markers and value tooltip support.",
    "uses": [
      "wa-tooltip"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-switch",
    "name": "Switch",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Immediate on/off setting control.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-textarea",
    "name": "Textarea",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Multiline text field with labels, hints, and resize behavior.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-time-input",
    "name": "Time Input",
    "category": "Forms",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental segmented time field with an optional picker.",
    "uses": [
      "wa-icon",
      "wa-popup"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-accordion",
    "name": "Accordion",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Coordinates one or more collapsible content sections.",
    "uses": [
      "wa-accordion-item"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-accordion-item",
    "name": "Accordion Item",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental labeled disclosure section used by an accordion.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-card",
    "name": "Card",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Groups related content and optional header, media, and footer slots.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-details",
    "name": "Details",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Single disclosure panel for secondary information.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-dialog",
    "name": "Dialog",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Modal surface for focused tasks and confirmations.",
    "uses": [
      "wa-button"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-divider",
    "name": "Divider",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Visual separator for related groups of content.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-drawer",
    "name": "Drawer",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Edge-anchored modal surface for navigation or secondary tasks.",
    "uses": [
      "wa-button"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-page",
    "name": "Page",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Responsive application shell with navigation, banner, and main slots.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-scroller",
    "name": "Scroller",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Overflow container with accessible scrolling affordances.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-split-panel",
    "name": "Split Panel",
    "category": "Layout",
    "kind": "component",
    "source": "webawesome",
    "description": "Alternative split API; prefer Kerf ResizableRegion for application panes.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-breadcrumb",
    "name": "Breadcrumb",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Ordered navigation trail for the current location.",
    "uses": [
      "wa-icon",
      "wa-breadcrumb-item"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-breadcrumb-item",
    "name": "Breadcrumb Item",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "One link or current-location item in a breadcrumb.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-pagination",
    "name": "Pagination",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental page navigation for a bounded result set.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tab",
    "name": "Tab",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Ecosystem tab label; prefer Kerf TabBar or SegmentedControl.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tab-group",
    "name": "Tab Group",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Ecosystem tabs; prefer Kerf TabBar or SegmentedControl.",
    "uses": [
      "wa-button",
      "wa-tab",
      "wa-tab-panel"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tab-panel",
    "name": "Tab Panel",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Ecosystem tab panel; prefer app-owned panels with Kerf navigation.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tree",
    "name": "Tree",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Specialized hierarchy; use only when the product requires tree behavior.",
    "uses": [
      "wa-tree-item"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tree-item",
    "name": "Tree Item",
    "category": "Navigation",
    "kind": "component",
    "source": "webawesome",
    "description": "Specialized tree row; use only as part of a required tree.",
    "uses": [
      "wa-checkbox",
      "wa-icon",
      "wa-spinner"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-badge",
    "name": "Badge",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Compact status or count label with semantic variants.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-callout",
    "name": "Callout",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Prominent contextual message with semantic variants.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-progress-bar",
    "name": "Progress Bar",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Linear indicator for determinate or indeterminate progress.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-progress-ring",
    "name": "Progress Ring",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Circular indicator for determinate or indeterminate progress.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-skeleton",
    "name": "Skeleton",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Placeholder shape for content that is still loading.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-spinner",
    "name": "Spinner",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Compact indeterminate activity indicator.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tag",
    "name": "Tag",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Compact categorization label with optional removal action.",
    "uses": [
      "wa-button"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-toast",
    "name": "Toast",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Placement-aware stack of transient notifications.",
    "uses": [
      "wa-toast-item"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-toast-item",
    "name": "Toast Item",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "One dismissible notification inside a toast stack.",
    "uses": [
      "wa-icon",
      "wa-progress-ring"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-tooltip",
    "name": "Tooltip",
    "category": "Feedback",
    "kind": "component",
    "source": "webawesome",
    "description": "Brief contextual label anchored to a control.",
    "uses": [
      "wa-popup"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-animated-image",
    "name": "Animated Image",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Specialized animated media; use only for a concrete product requirement.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-avatar",
    "name": "Avatar",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Person or entity image with initials fallback.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-carousel",
    "name": "Carousel",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Navigable horizontal or vertical collection of slides.",
    "uses": [
      "wa-icon",
      "wa-carousel-item"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-carousel-item",
    "name": "Carousel Item",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "One content slide inside a carousel.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-comparison",
    "name": "Comparison",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Specialized before-and-after media; use only when specifically required.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-icon",
    "name": "Icon",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Ecosystem icon renderer; use Kerf LucideIcon in application UI.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-markdown",
    "name": "Markdown",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental renderer for trusted Markdown content.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-qr-code",
    "name": "QR Code",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Scannable QR representation of a supplied value.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-zoomable-frame",
    "name": "Zoomable Frame",
    "category": "Media",
    "kind": "component",
    "source": "webawesome",
    "description": "Avoid for application UI; keep embedded-media behavior application-owned.",
    "uses": [
      "wa-icon"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-animation",
    "name": "Animation",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Declarative Web Animations API wrapper with preset effects.",
    "uses": [
      "select"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-format-bytes",
    "name": "Format Bytes",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Locale-aware byte and bit value formatter.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-format-date",
    "name": "Format Date",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Locale-aware date and time formatter.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-format-number",
    "name": "Format Number",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Locale-aware number, currency, unit, and percentage formatter.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-include",
    "name": "Include",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Loads and injects an external HTML fragment.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-intersection-observer",
    "name": "Intersection Observer",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Declaratively emits visibility changes for slotted content.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-mutation-observer",
    "name": "Mutation Observer",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Declaratively emits DOM mutation records for slotted content.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-popover",
    "name": "Popover",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Anchored non-modal surface built on popup positioning.",
    "uses": [
      "wa-popup"
    ],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-popup",
    "name": "Popup",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Preferred low-level anchored positioning when Tooltip or Popover do not fit.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-random-content",
    "name": "Random Content",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Experimental helper that selects one slotted item at random.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-relative-time",
    "name": "Relative Time",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Locale-aware human description of a date relative to now.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  },
  {
    "id": "wa-resize-observer",
    "name": "Resize Observer",
    "category": "Helpers",
    "kind": "component",
    "source": "webawesome",
    "description": "Declaratively emits size changes for slotted content.",
    "uses": [],
    "demoSource": "ui/ux-demo/webawesome-demos.tsx",
    "documentation": "ui/docs/webawesome-theme.md#coverage"
  }
] as const;
