/**
 * Guard for the animated demo-capture configs under
 * `site/scripts/demo-captures/*.json` (driven by domotion-svg to produce the
 * `site/public/demos/*.svg` previews).
 *
 * KF-272 / KF-273 / KF-274: the demos originally stitched their frames with
 * `crossfade` transitions. Because each frame is a full re-capture of the app,
 * a crossfade cross-dissolves the ENTIRE frame on every state change — two whole
 * UI states double-exposed — which reads as an unnatural full-screen "flash"
 * even when only a few elements actually changed. The fix is a hard cut on every
 * frame: `"transition": { "type": "cut" }`, which domotion emits as an instant
 * step-end opacity flip (no interpolation smear, no dip-to-blank).
 *
 * CRUCIAL: a *missing* `transition` does NOT give a hard cut — domotion defaults
 * an absent transition to a 300 ms `crossfade` (`frame.transition?.type ??
 * "crossfade"` in its animator). So this guard requires every frame to set
 * `type: "cut"` EXPLICITLY; merely checking for the absence of the literal
 * `"crossfade"` string would let the silent-default flash slip through (it did —
 * the first KF-274 attempt removed the transition key and the crossfade came
 * back). This keeps the "no full-screen flash on data change" intent enforceable.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { cwd } from 'node:process';

import { describe, expect, it } from 'vitest';

// vitest is invoked from the repo root, so cwd is the project directory.
const CONFIG_DIR = join(cwd(), 'site', 'scripts', 'demo-captures');
const SVG_DIR = join(cwd(), 'site', 'public', 'demos');

const configFiles = readdirSync(CONFIG_DIR).filter((f) => f.endsWith('.json'));
const svgFiles = readdirSync(SVG_DIR).filter((f) => f.endsWith('.svg'));

interface DemoFrame {
  transition?: { type?: string };
}
interface DemoConfig {
  output?: string;
  frames?: DemoFrame[];
}

describe('demo-capture configs', () => {
  it('finds the demo configs', () => {
    // Sanity: the directory should not be empty, or the guard below is vacuous.
    expect(configFiles.length).toBeGreaterThan(0);
  });

  for (const file of configFiles) {
    describe(file, () => {
      const raw = readFileSync(join(CONFIG_DIR, file), 'utf8');

      it('is valid JSON with a frames array', () => {
        const cfg = JSON.parse(raw) as DemoConfig;
        expect(Array.isArray(cfg.frames)).toBe(true);
        expect(cfg.frames!.length).toBeGreaterThan(0);
        expect(cfg.output).toMatch(/^site\/public\/demos\/.+\.svg$/);
      });

      it('has its output SVG committed (a config without its capture 404s on the site)', () => {
        // KF-330: the row-selector example shipped its capture config but the
        // SVG was never generated — nothing failed, and the site page 404'd.
        // Every config's `output` must resolve to a committed file; regenerate
        // with `bash site/scripts/demo-captures/capture-demos.sh` if this trips.
        const cfg = JSON.parse(raw) as DemoConfig;
        expect(existsSync(join(cwd(), cfg.output!))).toBe(true);
      });

      it('sets an explicit non-crossfade transition on every frame (KF-274: no full-screen dissolve flash)', () => {
        const cfg = JSON.parse(raw) as DemoConfig;
        // Every frame must declare an explicit transition that is NOT a
        // crossfade. A missing transition is NOT a hard cut — domotion silently
        // defaults it to a 300 ms crossfade, the very flash this guard exists to
        // prevent. `cut` (hard cut) and `magic-move` (match-cut bridge, used by
        // the kanban demo for cross-column card slides — KF-271) are both allowed:
        // neither cross-dissolves the whole frame.
        const allowed = new Set(['cut', 'magic-move']);
        const offenders = (cfg.frames ?? [])
          .map((frame, i) => ({ i, type: frame.transition?.type }))
          .filter((f) => !allowed.has(f.type ?? ''));
        expect(offenders).toEqual([]);
      });
    });
  }

  // Guard the committed SVGs against the "last frame fades to black" regression:
  // every hard-cut frame's opacity track must carry `step-end` so its visible
  // window holds then snaps, rather than interpolating opacity 1->0 over its whole
  // duration (a fade-out). domotion >= 0.18.0 emits `step-end` directly and keeps
  // it through SVGO (`optimize: true`), so no post-processing is needed — earlier
  // versions clobbered it during optimization and required a fix-cut-timing pass.
  // This assertion is the tripwire if a future domotion ever reintroduces the clobber.
  describe('rendered SVGs', () => {
    it('finds the committed demo SVGs', () => {
      expect(svgFiles.length).toBeGreaterThan(0);
    });

    it('has a capture config for every committed SVG (no orphans)', () => {
      // The inverse of the per-config output check: an SVG with no config can
      // never be regenerated by capture-demos.sh and silently drifts stale.
      const outputs = new Set(
        configFiles.map((f) => {
          const cfg = JSON.parse(readFileSync(join(CONFIG_DIR, f), 'utf8')) as DemoConfig;
          return cfg.output?.replace(/^site\/public\/demos\//, '');
        }),
      );
      const orphans = svgFiles.filter((f) => !outputs.has(f));
      expect(orphans).toEqual([]);
    });

    for (const file of svgFiles) {
      it(`${file}: every fv-N opacity track keeps step-end (no last-frame fade)`, () => {
        const svg = readFileSync(join(SVG_DIR, file), 'utf8');
        // Any `animation:fv-N <t>s …` that does not carry `step-end` would
        // interpolate (fade) instead of hard-cutting.
        const offenders = [...svg.matchAll(/animation:(fv-\d+) [0-9.]+s([^;}]*)/g)]
          .filter((m) => !m[2].includes('step-end'))
          .map((m) => m[1]);
        expect(offenders).toEqual([]);
      });
    }
  });

  // KF-330 follow-up: the site pages embed the demos as `/kerf/demos/<name>.svg`.
  // A reference to an SVG that was never captured/committed renders as a broken
  // image on the published site, and nothing else in the pipeline catches it
  // (Astro doesn't validate public/ asset paths).
  describe('site references', () => {
    const SITE_SRC = join(cwd(), 'site', 'src');
    const sourceFiles = readdirSync(SITE_SRC, { recursive: true, encoding: 'utf8' })
      .filter((f) => /\.(md|mdx|astro)$/.test(f));

    it('every /demos/*.svg image reference on the site resolves to a committed SVG', () => {
      const missing: string[] = [];
      for (const rel of sourceFiles) {
        const text = readFileSync(join(SITE_SRC, rel), 'utf8');
        for (const m of text.matchAll(/\/demos\/([\w-]+\.svg)/g)) {
          if (!svgFiles.includes(m[1])) missing.push(`${rel} → ${m[0]}`);
        }
      }
      expect(missing).toEqual([]);
    });

    it('finds at least one site reference (guard is not vacuous)', () => {
      const referenced = sourceFiles.some((rel) =>
        /\/demos\/[\w-]+\.svg/.test(readFileSync(join(SITE_SRC, rel), 'utf8')),
      );
      expect(referenced).toBe(true);
    });
  });
});
