import { execFileSync } from 'node:child_process';
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import process from 'node:process';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const repoRoot = resolve(import.meta.dirname, '../..');
const fixtureRoot = mkdtempSync(join(tmpdir(), 'kerf-release-package-'));
const betaVersion = '5.0.0-beta.2';

const packages = [
  ['kerfjs', '.'],
  ['eslint-plugin-kerfjs', 'eslint-plugin'],
  ['create-kerf-component', 'create-kerf-component'],
  ['@kerfjs/ui', 'ui'],
] as const;
const tarballs = new Map<string, string>();

function copy(relative: string): void {
  const destination = join(fixtureRoot, relative);
  mkdirSync(resolve(destination, '..'), { recursive: true });
  cpSync(join(repoRoot, relative), destination, { recursive: true });
}

function packedText(tarball: string, relative: string): string {
  return execFileSync('tar', ['-xOf', tarball, `package/${relative}`], {
    encoding: 'utf8',
  });
}

beforeAll(() => {
  for (const relative of [
    'scripts/prepare-release-package.mjs',
    'package.json',
    'ai/manifest.json',
    'setup',
    'eslint-plugin/package.json',
    'eslint-plugin/index.js',
    'create-kerf-component/package.json',
    'create-kerf-component/index.js',
    'create-kerf-component/catalog.js',
    'create-kerf-component/component-metadata.schema.json',
    'create-kerf-component/component-catalog-v2.schema.json',
    'create-kerf-component/template',
    'ui/package.json',
    'ui/ai/public-api-signatures-v1.md',
    'ui/ai/webawesome-jsx-signatures-v1.md',
  ])
    copy(relative);

  for (const [name] of packages) {
    execFileSync(
      process.execPath,
      [
        join(fixtureRoot, 'scripts/prepare-release-package.mjs'),
        name,
        betaVersion,
        '--root',
        fixtureRoot,
      ],
      { stdio: 'pipe' },
    );
  }

  for (const [name, relative] of packages) {
    const out = join(fixtureRoot, 'packed', name.replaceAll('/', '-'));
    mkdirSync(out, { recursive: true });
    const packOutput = execFileSync(
      'npm',
      ['pack', '--ignore-scripts', '--json', '--pack-destination', out],
      {
        cwd: join(fixtureRoot, relative),
        encoding: 'utf8',
        env: {
          ...process.env,
          HUSKY: '0',
          npm_config_cache: join(fixtureRoot, 'npm-cache'),
        },
      },
    );
    const packResult = JSON.parse(
      packOutput.slice(packOutput.indexOf('[\n')),
    ) as Array<{
      filename: string;
    }>;
    tarballs.set(name, join(out, basename(packResult[0].filename)));
  }
}, 30_000);

afterAll(() => rmSync(fixtureRoot, { recursive: true, force: true }));

describe('release package preparation', () => {
  it('packs synchronized beta metadata into all four release artifacts', () => {
    const coreTarball = tarballs.get('kerfjs')!;
    expect(JSON.parse(packedText(coreTarball, 'package.json')).version).toBe(
      betaVersion,
    );
    expect(
      JSON.parse(packedText(coreTarball, 'ai/manifest.json')).kerfjsVersion,
    ).toBe(betaVersion);
    expect(packedText(coreTarball, 'setup/cli.mjs')).toContain(
      '#!/usr/bin/env node',
    );

    const pluginTarball = tarballs.get('eslint-plugin-kerfjs')!;
    expect(JSON.parse(packedText(pluginTarball, 'package.json')).version).toBe(
      betaVersion,
    );
    expect(packedText(pluginTarball, 'index.js')).toContain(
      `version: '${betaVersion}'`,
    );

    const createTarball = tarballs.get('create-kerf-component')!;
    expect(JSON.parse(packedText(createTarball, 'package.json')).version).toBe(
      betaVersion,
    );
    const template = JSON.parse(
      packedText(createTarball, 'template/package.json'),
    );
    expect(template.peerDependencies.kerfjs).toBe('^5.0.0-0');
    expect(template.devDependencies.kerfjs).toBe(`^${betaVersion}`);
    expect(packedText(createTarball, 'catalog.js')).toContain(
      'runCatalogCommand',
    );
    expect(
      JSON.parse(packedText(createTarball, 'component-metadata.schema.json'))
        .title,
    ).toBe('Kerf consumer component metadata source');
    expect(
      JSON.parse(packedText(createTarball, 'component-catalog-v2.schema.json'))
        .title,
    ).toBe('Kerf UI composition catalog v2');

    const uiTarball = tarballs.get('@kerfjs/ui')!;
    const uiManifest = JSON.parse(packedText(uiTarball, 'package.json'));
    expect(uiManifest.version).toBe(betaVersion);
    expect(uiManifest.peerDependencies.kerfjs).toBe('^5.0.0-0');
    expect(packedText(uiTarball, 'ai/public-api-signatures-v1.md')).toContain(
      `@kerfjs/ui@${betaVersion}\` and \`kerfjs@${betaVersion}`,
    );
    expect(
      packedText(uiTarball, 'ai/webawesome-jsx-signatures-v1.md'),
    ).toContain(`@kerfjs/ui@${betaVersion}`);
  });

  it('builds a project generated by the packed initializer with TypeScript 6', () => {
    const artifactRoot = join(fixtureRoot, 'create-artifact');
    const generatedRoot = join(fixtureRoot, 'generated-component');
    mkdirSync(artifactRoot, { recursive: true });
    execFileSync('tar', [
      '-xf',
      tarballs.get('create-kerf-component')!,
      '-C',
      artifactRoot,
    ]);
    execFileSync(process.execPath, [
      join(artifactRoot, 'package/index.js'),
      generatedRoot,
    ]);

    // Exercise the generated package with the repository's installed build
    // toolchain without a network-dependent install inside the test fixture.
    symlinkSync(
      join(repoRoot, 'node_modules'),
      join(generatedRoot, 'node_modules'),
      'dir',
    );
    const typescriptPackage = JSON.parse(
      readFileSync(
        join(generatedRoot, 'node_modules/typescript/package.json'),
        'utf8',
      ),
    );
    expect(typescriptPackage.version).toMatch(/^6\./);

    expect(() =>
      execFileSync('npm', ['run', 'build'], {
        cwd: generatedRoot,
        stdio: 'pipe',
        env: {
          ...process.env,
          npm_config_cache: join(fixtureRoot, 'npm-cache'),
        },
      }),
    ).not.toThrow();
    expect(() =>
      execFileSync('npm', ['run', 'catalog:check'], {
        cwd: generatedRoot,
        stdio: 'pipe',
      }),
    ).not.toThrow();
    expect(() =>
      execFileSync('npm', ['publish', '--dry-run', '--offline', '--json'], {
        cwd: generatedRoot,
        stdio: 'pipe',
        env: {
          ...process.env,
          npm_config_cache: join(fixtureRoot, 'npm-cache'),
        },
      }),
    ).not.toThrow();
    expect(
      readFileSync(join(generatedRoot, 'dist/counter.d.ts'), 'utf8'),
    ).toContain('createCounter');
    expect(
      readFileSync(join(generatedRoot, 'dist/counter.js'), 'utf8'),
    ).toContain('createCounter');
  }, 40_000);

  it('keeps preparation and packing outside every OIDC publish job and publishes local paths', () => {
    const workflows = [
      'release.yml',
      'release-eslint-plugin.yml',
      'release-create-kerf-component.yml',
      'release-ui.yml',
    ];

    const releasePackage = join(fixtureRoot, 'release-package');
    mkdirSync(releasePackage, { recursive: true });
    const coreTarball = tarballs.get('kerfjs')!;
    cpSync(coreTarball, join(releasePackage, basename(coreTarball)));

    for (const workflow of workflows) {
      const source = readFileSync(
        join(repoRoot, '.github/workflows', workflow),
        'utf8',
      );
      const publishJob = source.slice(source.indexOf('  npm-publish:\n'));
      const beforePublish = source.slice(0, source.indexOf('  npm-publish:\n'));
      const publishCommands = [
        ...publishJob.matchAll(/run: (npm publish (\S+)[^\n]*)/g),
      ].map((match) => ({ command: match[1], artifact: match[2] }));

      expect(beforePublish).toContain('scripts/prepare-release-package.mjs');
      expect(beforePublish).toContain('npm pack --ignore-scripts');
      expect(publishJob).toContain('actions/download-artifact@');
      expect(publishCommands).toHaveLength(2);
      expect(publishCommands[0]!.command).not.toContain('--tag beta');
      expect(publishCommands[1]!.command).toContain('--tag beta');
      expect(publishJob).not.toContain('scripts/prepare-release-package.mjs');
      expect(publishJob).not.toContain('npm version');
      expect(publishJob).not.toContain('npm install');
      expect(publishJob).not.toContain('actions/checkout@');
      expect(publishJob).toContain(
        "node-version: '${{ env.PUBLISH_NODE_VERSION }}'",
      );

      for (const { artifact } of publishCommands) {
        const expandedArgument = artifact.replace(
          '*.tgz',
          basename(coreTarball),
        );
        expect(() =>
          execFileSync(
            'npm',
            [
              'publish',
              expandedArgument,
              '--dry-run',
              '--offline',
              '--ignore-scripts',
              // npm 11+ rejects every prerelease publish without an explicit
              // non-latest dist-tag, including dry runs. The fixture tarball
              // is intentionally a beta even when validating the stable
              // workflow's local artifact path; this tag applies only to the
              // validation command, while the assertions above keep the
              // actual stable publish command tag-free.
              '--tag',
              'beta',
            ],
            {
              cwd: fixtureRoot,
              stdio: 'pipe',
              env: {
                ...process.env,
                npm_config_cache: join(fixtureRoot, 'npm-cache'),
              },
            },
          ),
        ).not.toThrow();
      }
    }
  }, 40_000);
});
