import { defineConfig } from 'tsup';

const entries = [
  'index',
  'badge',
  'chip',
  'css-values',
  'lucide-icon',
  'disclosure-arrow',
  'toolbar',
  'toolbar-control-group',
  'surface-scaffold',
  'popup-menu',
  'popup-menu-register',
  'toolbar-text',
  'text',
  'floating-toolbar',
  'list',
  'row',
  'grid',
  'spacer',
  'list-action-row',
  'list-item',
  'list-header',
  'list-inset-control',
  'list-inset-text',
  'content-item',
  'resizable-region',
  'wire-resizable-regions',
  'device-class',
  'app-tab',
  'catalog',
  'catalog-resources',
  'wire-catalog',
  'tab-bar',
  'wire-tab-bars',
  'wire-scroll-dividers',
  'wire-toolbar-visibility',
  'nav-stack',
  'wire-nav-stack',
  'wire-content-items',
  'split-view',
  'pane',
  'workbench',
  'collapsible-panel',
  'wire-sidebar',
  'tab-scaffold',
  'wire-tab-scaffold',
  'wire-workbench',
  'loading-spinner',
  'skeleton',
  'sunken-panel',
  'select',
  'segmented-control',
  'token-search-field',
  'token-search-model',
  'wire-token-search-fields',
  'select-register',
  'help-tags-register',
  'webawesome',
  'state-banner',
  'empty-state',
  'value-table',
];

export default defineConfig({
  entry: entries.map(
    (entry) =>
      `src/${entry}.${entry === 'index' || entry === 'css-values' || entry === 'select-register' || entry === 'popup-menu-register' || entry === 'help-tags-register' || entry === 'webawesome' || entry === 'device-class' || entry === 'catalog-resources' || entry === 'token-search-model' || entry.startsWith('wire-') ? 'ts' : 'tsx'}`,
  ),
  format: ['esm'],
  outDir: 'dist',
  target: 'es2022',
  platform: 'neutral',
  splitting: true,
  clean: true,
  sourcemap: true,
  dts: { compilerOptions: { ignoreDeprecations: '6.0' } },
  treeshake: true,
  external: ['kerfjs', 'kerfjs/jsx-runtime', '@awesome.me/webawesome'],
});
